baseURL = 'https://nicholasf.github.io/'
languageCode = 'en-us'
title = 'quizzical...'
theme = 'PaperMod'
[pagination]
  pagerSize = 10

[params]
  description = ""
  author = "nicholasf"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = false

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/nicholasf"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/nicholasfaiz"
